### ISSUE TITLE
Validation accepts invalid SPDX YAML files

### ISSUE THREAD

**Issue by sschuberth** [spdx/spdx-java-jackson-store#21] opened 2021-09-17 08:41 UTC
For testing, I did download https://github.com/spdx/spdx-spec/blob/3d156919a06c07781bd47dc26c75efcfc9df21cd/examples/SPDXYAMLExample-2.2.spdx.yaml and changed `relationships` (plural) to `relationship` (singular) in line 636:

https://github.com/spdx/spdx-spec/blob/3d156919a06c07781bd47dc26c75efcfc9df21cd/examples/SPDXYAMLExample-2.2.spdx.yaml#L363

This deliberately renders the syntax invalid. However, uploading the broken file for validation at https://tools.spdx.org/app/validate/ shows that the SPDX document is valid:

![image](https://user-images.githubusercontent.com/349154/133752662-ea4731bc-e0d8-413d-8bf7-bfec4f38a2a9.png)

**Comment by goneall** [comment] 2021-09-17 18:13
The issue is related to the JSON-LD file generated by the tools-java [OwlToJSONContext](https://github.com/spdx/tools-java/blob/master/src/main/java/org/spdx/tools/schema/OwlToJsonContext.java) utility.

This file is used to interpret the property names.  It looks like for every list property, it creates a singular type in [this line](https://github.com/spdx/tools-java/blob/89cc3c1d48ff264241d7e6fc596007c271c9cfd4/src/main/java/org/spdx/tools/schema/OwlToJsonContext.java#L85) then creates the plural version of the type with the additional `@set` attribute.

I added an issue against the spec to discuss the JSON-LD context file changes: https://github.com/spdx/spdx-spec/issues/570

If we decide to fix the JSON-LD context file, I'll move this issue over to the tools-java repo.  If we decide not to fix the JSON-LD, I'll see if there is some way to generate an error.  Based on the current design, adding a validation warning for this could be challenging.

**Comment by sschuberth** [comment] 2021-09-18 16:48
> Based on the current design, adding a validation warning for this could be challenging.

Is that maybe a reason to re-think the current design for SPDX 3.0?

**Comment by goneall** [comment] 2021-09-18 18:03
> Is that maybe a reason to re-think the current design for SPDX 3.0?

It is more of an application design issue rather than an SPDX spec issue.  We separated the serialization/deserialization code from the model through a well defined interface which has the advantage of easily adding additional serialization formats.  Currently, all the validation uses the model code and isn't even aware of how the data was deserialized.  We would need to add an interface to collect warnings from the layer that does the serialization/deserialization.

**Comment by goneall** [comment] 2021-10-13 01:30
Resolved with PR #22

**Closed by goneall** 2021-10-13 01:30 UTC
